In [2]:
# utilities

def get_data(day):
    # e.g. get_data(d1)
    with open(f'data/{day}.txt') as f:
        lines = f.read().splitlines()
    return lines

## D1
Input data are lines representing calories of food items, carried by each elf.  
Next elf is demarcated by a blank line.  


In [4]:
lines = get_data('d1')

In [6]:
# Part 1: Find the elf with the highest total of calories
max_elf_calories = 0
calorie_count = 0 

for line in lines:
    if line:
        calorie_count += int(line)
    else:
        max_elf_calories = max(max_elf_calories, calorie_count)
        calorie_count = 0
print(max_elf_calories)
    

68802


In [17]:
# Part 2: Find the total of the top 3 elves calories
all_elves_calories = []
calorie_count = 0 

for line in lines:
    if line:
        calorie_count += int(line)
    else:
        all_elves_calories.append(calorie_count)
        calorie_count = 0
print(sorted(all_elves_calories)[-3:])
print(sum(sorted(all_elves_calories)[-3:]))

[67860, 68708, 68802]
205370


## D2
Play rock paper scissors against the elves with a preset strategy (cheat guide)

In [14]:
# loss = 0, draw = 3, win = 6
# scores for RPS rock = 1, paper = 2, scissors = 3
# Rock Paper Scissors ABC (opponent) XYZ (you)
# rock > paper > scissors > rock

data = get_data('d2')

# create a linked list of rock paper scissors
def linked_list()


match = {"A": "X", "B": "Y", "C": "Z"}
score = 0

for line in data: 
    elf, you = line.split()
    if you == "X": 
        score += 1
    elif you == "Y": 
        score += 2
    elif you == "Z":
        score += 3
    if match[elf] == you: # draw
        score += 3
    elif match[elf] == "X" and you == "Y": # win
        score += 6
    elif match[elf] == "Y" and you == "Z": # win
        score += 6
    elif match[elf] == "Z" and you == "X": # win
        score += 6
    # ignore losses
score
    

12772

In [45]:
# Part 2
# "Anyway, the second column says how the round needs to end: X means you need to lose, Y means you need to end the round in a draw, and Z means you need to win. Good luck!"
dict = {"AX": 3, "AY": 1 + 3, "AZ": 2 + 6, "BX": 1, "BY": 2 + 3, "BZ": 3 + 6, "CX": 2, "CY": 3 + 3, "CZ": 1 + 6}

score = 0
for line in data:
    score += dict[line.replace(" ", "")]
score

11618

## D3
Rearrange items in elves rucksacks. Each rucksack has 2 compartments. All items of the same type must go in the same compartment.  
Each char represents an item (upper and lower are different).  
Compartments same size, so first half of line is c1, send is c2

Item priority a-z, A-Z
What is sum of priorities of items that appear in both compartments


In [ ]:
bags = get_data('d3')

In [78]:
score = 0
for bag in bags:
    # split bag in half
    c1 = bag[:len(bag)//2]
    c2 = bag[len(bag)//2:]
    s = list(set(c1).intersection(set(c2)))[0]
    if s.isupper():
        score += ord(s)-64+26
    else:
        score += ord(s)-96
score


8176

In [82]:
# part 2
# split bags into groups of 3, find common item type and sum priorities
score = 0 
for i in range(0, len(bags), 3):
    b1, b2, b3 = bags[i:i+3]
    s = list(set(b1).intersection(set(b2), set(b3)))[0]
    if s.isupper():
        score += ord(s)-64+26
    else:
        score += ord(s)-96
score

2689

## D4
How many sections fully contain the other

In [58]:
sections = get_data("d4")
sections = [[list(map(int,x.split('-'))) for x in y.split(',')] for y in sections]
sections[0] 

[[98, 99], [3, 97]]

In [59]:
# [1,10], [2,3]

count = 0
for section in sections:
    if (section[0][0] <= section[1][0]) and (section[0][1] >= section[1][1]):
        count += 1 # section 1 contains section 2
        continue # avoid double counting
    elif section[1][0] <= section[0][0] and section[1][1] >= section[0][1]:
        count += 1 # section 2 contains section 1
        continue
count

459

In [60]:
# [1,10], [2,3]
# part 2 
# how many pairs overlap
count = 0
for section in sections:
    # check if section 1 is below section 2
    if section[0][0] < section[1][0] and section[0][1] < section[1][0]:
        continue
    # check if section 1 is above section 2
    elif section[0][0] > section[1][1] and section[0][1] > section[1][1]:
        continue
    else:
        count+=1
count

779

Expanding the ranges and using set intersections could have been interesting

## d5

In [119]:
data = get_data('d5')
start = data[:9]
moves = data[10:]

# turn into pairs of operations, expanding the repetitions
input = [list(map(int, m.replace('move ', '').replace(' from ', ',').replace(' to ', ',').split(','))) for m in moves]
input[0][0] * [[input[0][1], input[0][2]]]
movelist = []
for i in input:
    movelist.extend((i[0] * [[i[1], i[2]]]))
movelist[:5]

[[4, 3], [4, 3], [4, 3], [4, 3], [4, 3]]

In [122]:
start

['[F]         [L]     [M]            ',
 '[T]     [H] [V] [G] [V]            ',
 '[N]     [T] [D] [R] [N]     [D]    ',
 '[Z]     [B] [C] [P] [B] [R] [Z]    ',
 '[M]     [J] [N] [M] [F] [M] [V] [H]',
 '[G] [J] [L] [J] [S] [C] [G] [M] [F]',
 '[H] [W] [V] [P] [W] [H] [H] [N] [N]',
 '[J] [V] [G] [B] [F] [G] [D] [H] [G]',
 ' 1   2   3   4   5   6   7   8   9 ']

In [123]:
# turn crates into list of lists
crates = [''] * 9
for row in start[:-1]: # skip last row
    for i in range(0, 9):
        # want 2, 7, 12, 17 etc
        # 0, 1, 2, 3,
        crates[i] += row[4*i+1]
crates = [x.strip() for x in crates]
crates

['FTNZMGHJ',
 'JWV',
 'HTBJLVG',
 'LVDCNJPB',
 'GRPMSWF',
 'MVNBFCHG',
 'RMGHD',
 'DZVMNH',
 'HFNG']

In [106]:
for move in movelist:
    # print(move)
    # print(crates[move[0]-1], crates[move[1]-1])
    crates[move[1]-1] = (crates[move[0]-1][0]) + crates[move[1]-1]
    crates[move[0]-1] = crates[move[0]-1][1:]
    # print(crates[move[0]-1], crates[move[1]-1])
crates

['T',
 'DPHJNGC',
 'CNBPVGLDSRRMMHZNLJVWMGFHNGHVGM',
 'HFN',
 'VBFWJZDM',
 'HB',
 'J',
 'TFV',
 'G']

In [111]:
answer = ''
for x in crates:
    answer += x[0]
answer

'TDCHVHJTG'

In [140]:
# part 2
# my decision to expand each moves into 1 operation per crate was a bad idea
data = get_data('d5')
start = data[:9]
moves = data[10:]

input = [list(map(int, m.replace('move ', '').replace(' from ', ',').replace(' to ', ',').split(','))) for m in moves]
input[:5]

[[6, 4, 3], [5, 8, 9], [1, 4, 5], [1, 4, 5], [2, 2, 7]]

In [141]:
# turn crates into list of lists
crates = [''] * 9
for row in start[:-1]: # skip last row
    for i in range(0, 9):
        # want 2, 7, 12, 17 etc
        # 0, 1, 2, 3,
        crates[i] += row[4*i+1]
crates = [x.strip() for x in crates]
crates

['FTNZMGHJ',
 'JWV',
 'HTBJLVG',
 'LVDCNJPB',
 'GRPMSWF',
 'MVNBFCHG',
 'RMGHD',
 'DZVMNH',
 'HFNG']

In [142]:
start

['[F]         [L]     [M]            ',
 '[T]     [H] [V] [G] [V]            ',
 '[N]     [T] [D] [R] [N]     [D]    ',
 '[Z]     [B] [C] [P] [B] [R] [Z]    ',
 '[M]     [J] [N] [M] [F] [M] [V] [H]',
 '[G] [J] [L] [J] [S] [C] [G] [M] [F]',
 '[H] [W] [V] [P] [W] [H] [H] [N] [N]',
 '[J] [V] [G] [B] [F] [G] [D] [H] [G]',
 ' 1   2   3   4   5   6   7   8   9 ']

In [143]:
# for each move in input, n, a, b, move n crates from a to b
for move in input:
    # print(move)
    # print(crates)
    crates[move[2]-1] = (crates[move[1]-1][0:move[0]]) + crates[move[2]-1]
    crates[move[1]-1] = crates[move[1]-1][move[0]:]
    # print(crates)
crates

['N',
 'GGGGMRV',
 'CNWBJHLJZRZNBCVPFVNNVHFTGBMWDD',
 'MSH',
 'PHFJGTMH',
 'JM',
 'L',
 'HFD',
 'V']

In [144]:
answer = ''
for x in crates:
    answer += x[0]
answer

'NGCMPJLHV'

## D6
Fix the walkie talkie by identifying a start of packet marker: 4 consecutive chars that are all different.  
P1, P2 - finding the packet marker, 4 chars, and message marker, 14 chars

In [176]:
input = get_data('d6')

In [180]:
packet_marker = [*input[0][:4]] # keep last 4 packets in this array
message_marker = [*input[0][:14]] # keep last 4 packets in this array
packet_marker, message_marker

(['d', 'c', 'b', 'c'],
 ['d', 'c', 'b', 'c', 's', 'b', 'b', 'l', 'h', 'h', 'g', 'd', 'g', 's'])

In [181]:
for i in range(4, len(input[0])):
    if len(set(packet_marker)) == 4:
        print(f"Part 1 - Marker found at last packet: {i}")
        break

    packet_marker.pop(0)
    packet_marker.append(input[0][i])

Part 1 - Marker found at last packet: 1238


In [182]:
for i in range(14, len(input[0])):
    if len(set(message_marker)) == 14:
        print(f"Part 2 - Marker found at last packet: {i}")
        break
    message_marker.pop(0)
    message_marker.append(input[0][i])
        

Part 2 - Marker found at last packet: 3037


## D7

In [208]:
import re

commands = get_data('d7')

# we need to construct a tree of folders, each should have its parent and its size
folders = {'/': {'parent': None, 'size': 0}} # root folder

current_dir = [] # list of directories visited in order

# we need recursion to parse the tree
for command in commands:

    # keep track of directory
    if command == "$ cd ..":     
        if folders[current_dir]['parent'] == None:
            continue
        current_dir = folders[current_dir]['parent']
    elif command[:4] == "$ cd": 
        current_dir = command[5:]
    
    if command[:4] == "dir ":
        if command[4:] not in folders:
            folders[command[4:]] = {'parent': current_dir, 'size': 0}
        continue
    else:
        # folders[current_dir]['size'] += 
        match = re.match(r"(\d+)", command)
        if match:
            folders[current_dir]['size'] += int(match.groups()[0])

# folders

In [209]:
def add_to_parents(folder):
    if folder == '/':
        return
    folders[folders[folder]['parent']]['size'] += folders[folder]['size']
    add_to_parents(folders[folder]['parent'])

for folder in folders:
    add_to_parents(folder)

In [210]:
sum([x[1]['size'] for x in folders.items() if x[1]['size'] <= 100000])

# 1834636

1834636

consulting reddit... :/ 

In [217]:
def get_fs_size(filename): 
    with open(filename) as file: 
        lines = file.readlines()
        fs = {('/',):0} 
        path = []
        for line in lines: 
            match line.split(): 
                case ["$", "ls"]: 
                    pass
                case ["$", "cd", ".."]:
                    path = path[:-1]

                case ["$", "cd", directory]:
                    path += [directory]

                case["dir", directory]:
                    fs.setdefault(tuple(path + [directory]), 0)

                case[size, filename]:
                    for i in range(1, len(path) + 1):
                        fs[tuple(path[:i])] += int(size)

    return fs 

fs = get_fs_size("data/d7.txt")
over_10k = [x for x in fs.values() if x <= 100000]

print("===part 1===\n", sum([x for x in fs.values() if x <= 100000]))

print("=== part 2 ===") 
FS_SIZE = 70000000 
SPACE_NEEDED = 30000000
unused = FS_SIZE - fs[("/",)] 
size_to_del = SPACE_NEEDED - unused 
big_enough_dirs = {k:v for (k,v) in fs.items() if v >= size_to_del}
print(" - Qualifying Dirs ") 
for k, v in big_enough_dirs.items(): print("    - ", end="") 
print(*k, sep="/", end="") 
print(": ", v)
print("Smallest: ", min(big_enough_dirs.values()))

===part 1===
 1844187
=== part 2 ===
 - Qualifying Dirs 
    -     -     -     -     -     -     -     -     -     -     - //nhqwt/mcnjwwfr/dqp/rpchqq/lrphzrv:  6721126
Smallest:  4978279


## D8
Lets try again after not doing too well on d7

In [269]:
import numpy as np

data = get_data('d8')

transpose_data = np.array([[*row] for row in data]).T.tolist()
transpose_data = [''.join(row) for row in transpose_data]

In [276]:
data[:5]

['301201331333030024002151134115545441525510053410321024643223304253251423014345311431413433341211111',
 '210313031411030140245452501003514242514125366210551353634546632015232323540022212401412031113310333',
 '201223331222432221305443412445304401201165033624245311620346242360420521343514132520204104244200322',
 '210003034413133345421153101053132524226234460546142402452466345321440520524311212410303224012242000',
 '002232200024321241105051144044530503201446133504652500410463241436361361002024122340512441243222203']

In [275]:
transpose_data[:5]

['322201003014101243412451520142400351421215541303454563106045011235431142153245230204004203212011200',
 '010100130231043101142550355411030135112504355511233421503353503052544334550343002311331214030230201',
 '101022142232001203421351242443202542523353465032340255260630563005513342024300430424022043122023113',
 '232020442224043211234104244251453606112111443104260106612621405250420123542353334421213144014221222',
 '012032321001243032152134322141406026236525420366061006060440554510661145200531142141310233004144332']

In [313]:
# for each row we can go row-wise, columnn-wise to check previous visilbity, then go backwards
# then transpose it and do the same thing?

# avoid double counting by saving the index
all_visible = []

def count_row_visibility(row, row_num, backwards=False):
    if backwards:
        # print('backwards')
        all_visible.append((row_num, 98))
    else:
        all_visible.append((row_num, 0))
    seen = [row[0]]
    # print(f"Visible: {row[0]}")
    # print(all_visible)
    for col_num, num in enumerate(row):
        if num > max(seen):
            # print(f"Visible: {num}")
            if backwards:
                all_visible.append((row_num, 98 - col_num))
                # print('backwards', all_visible)
            else:
                all_visible.append((row_num, col_num))
                # print(all_visible)
        seen.append(num)
    return

for i, row in enumerate(data):
    count_row_visibility(row, i)
    count_row_visibility(row[::-1], i, backwards=True)
for i, row in enumerate(transpose_data):
    count_row_visibility(row, i)
    count_row_visibility(row[::-1], i, backwards=True)
print(f"Total visible trees is {len(set(all_visible))}")

Total visible trees is 1770


In [314]:
# not correct...

## D9

In [317]:
data=get_data('d9')
data[:10]

['U 2', 'D 2', 'R 2', 'U 2', 'D 1', 'L 2', 'R 2', 'D 1', 'R 2', 'D 1']

In [404]:
H = T = (0, 0) # initial_state

def move_to_vector(move):
    direction, scale = move.split(' ') # U 2
    vector = {"U": (0, 1), "D": (0, -1), "L": (-1, 0), "R": (1, 0)}[direction]
    return (vector, int(scale), direction)

H_path = [H]
T_path = [T]

# T moves if H[0] - T[0] > 0 AND H[1] - T[1] > 0
def move_T(H, T, move):
    vector, scale, direction = move_to_vector(move)
    # print(f"Move: {move}")
    for _ in range(scale):        
        # move head
        H = (H[0] + vector[0], H[1] + vector[1]) 
        # check if tail moves
        if H[0] - T[0] > 1 or H[1] - T[1] > 1:
            # move tail
            # print("move tail from: ", T)
            if direction == "U" or direction == "D":
                T =  (H[0], T[1] + vector[1])
            elif direction == "L" or direction == "R":
                T =  (T[0] + vector[0], H[1])
            # print("move tail to: ", T)
            
        H_path.append(H)
        T_path.append(T)
    return H, T

for move in data:
    H, T = move_T(H, T, move)
len(set(T_path))

# too low again 1580


1580

In [401]:
# visualise for debugging

for H,T in zip(H_path[:30], T_path[:30]):    
    grid = np.zeros((9, 9))
    grid[T[0] + 4, T[1] + 4] = 1
    grid[H[0] + 4, H[1] + 4] = 2
    print(H, T)
    print(grid)


(0, 0) (0, 0)
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(0, 1) (0, 0)
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(0, 2) (0, 1)
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(0, 1) (0, 1)
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 

IndexError: index 9 is out of bounds for axis 0 with size 9

## D10

In [645]:
data = get_data('d10')
monkeys = [data[i:i+7] for i in range(0,len(data),7)]
# monkeys


In [646]:
processed = [
    [0, [57], ["*", 13] , 11, [3,2]],
    [1, [58, 93, 88, 81, 72, 73, 65], ["+", 2] , 7, [6,7]],
    [2, [65, 95], ["+", 6] , 13, [3,5]],
    [3, [58, 80, 81, 83], ["*", "old"] , 5, [4,5]],
    [4, [58, 89, 90, 96, 55], ["+", 3] , 3, [1,7]],
    [5, [66, 73, 87, 58, 62, 67], ["*", 7] , 17, [4,1]],
    [6, [85, 55, 89], ["+", 4] , 2, [2,0]],
    [7, [73, 80, 54, 94, 90, 52, 69, 58], ["+", 7] , 19, [6,0]]
]

In [647]:
# operation shows how your worry level changes when monkey inspects the item
# before monkey testing, your worry level divides by 3 and rounds down

class Monkey():
    def __init__(self, number, starting_items, operation, test, possible_monkey_recipients):
        self.number = number
        self.starting_items = starting_items
        self.current_items = starting_items
        self.operation = operation
        self.test = test
        self.possible_monkey_recipients = possible_monkey_recipients
        self.inspected = 0

    def __repr__(self):
        return f"{self.number}: {self.inspected}"

    def __len__(self):
        return len(self.current_items)
    
    def name(self):
        return self.number

    def do_operation(self, worry_level):
        operation = self.operation
        # print(f"Monkey {self.number} operation: {operation}")
        if operation[1] == "old":
            return worry_level * worry_level
        if operation[0] == "*":
            return worry_level * operation[1]
        elif operation[0] == "+":
            return worry_level + operation[1]

    
    def do_test(self, worry_level):
        # print(f"Monkey {self.number} test: {self.test}")
        if worry_level % self.test == 0:
            return self.possible_monkey_recipients[0]
        else:
            return self.possible_monkey_recipients[1]
        

    def inspect(self, item):
        # apply operation
        # print(f"Monkey {self.number} inspects item {item}...")
        worry_level = item
        worry_level = self.do_operation(worry_level)
        # worry_level = worry_level // 3 # p2 strike out
        monkey_recipient = self.do_test(worry_level)
        # print(f"Monkey {self.number} throws item {item} to monkey {monkey_recipient}")
        self.inspected += 1
        return monkey_recipient, worry_level


In [615]:
# testing
test_monkeys = [
    [0 ,[79, 98],["*", 19], 23, [2,3]],
    [1 ,[54, 65, 75, 74],["+", 6], 19, [2,0]],
    [2 ,[79, 60, 97],["*", "old"], 13, [1,3]],
    [3 ,[74],["+", 3], 17, [0,1]]
]

test_monkeys = monkeys = [Monkey(*monkey) for monkey in test_monkeys]

for round in range(20):
    for monkey in test_monkeys:
        # print(monkey)
        for item in monkey.current_items:
            receipient, worry_level = monkey.inspect(item)
            monkeys[receipient].current_items.append(worry_level)
        monkey.current_items = []
        # print("------------- Next Monkey --------------")
    # print(f"Round {round} complete")

# Answers
# Monkey 0 inspected items 101 times.
# Monkey 1 inspected items 95 times.
# Monkey 2 inspected items 7 times.
# Monkey 3 inspected items 105 times.

# print(monkeys)

In [648]:
from tqdm import tqdm

monkeys = [Monkey(*monkey) for monkey in processed]
# print(monkeys)

# part 1 range 20, part 2 range 10_000 
def run_simulation(monkeys):
    for round in tqdm(range(10_000)):
        for monkey in monkeys:
            # print(monkey)
            for item in monkey.current_items:
                receipient, worry_level = monkey.inspect(item)
                worry_level =  worry_level % 9699690

                monkeys[receipient].current_items.append(worry_level)
            monkey.current_items = []
            # print("------------- Next Monkey --------------")
        # print(f"Round {round} complete")
    print(monkeys)

run_simulation(monkeys)

# use cProfile to see what is happening
# import cProfile
# cProfile.run('run_simulation(monkeys)')
# see that do_operation is growing fastest, followed by do_test



100%|██████████| 10000/10000 [00:00<00:00, 26492.72it/s]

[0: 165766, 1: 161105, 2: 159985, 3: 9209, 4: 18375, 5: 166922, 6: 13590, 7: 169205]


In [649]:
counts = sorted([m.inspected for m in monkeys], reverse=True)[:2]
counts[0] * counts[1]

# P1 121450
# p2 28244037010

28244037010

## D11

In [18]:
# input is a grid
# starting location is S with elevation a, ending location is E with elevation z
# a is lowest elevation, z is highest
# You can transverse at most 1 elevation unit up at a time, but unlimited down, so a -> b, but not a -> c, but d -> a is ok

#  So the grid is a weighted graph and we should use dijkstra's algorithm
# https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm

data = get_data('d11')

print(f"Grid of {len(data[0])} by {len(data)}")



Grid of 101 by 41


In [56]:
def create_path_grid(data):
    path_grid = []
    mapping = {"S": "S", "E": "E"}
    for row in data:
        path_grid.append([mapping[c] if c in mapping else "." for c in row ])
    return path_grid

def visualise_path_grid(path_grid):    
    with open('d11_path.txt', 'w') as f:
        for line in path_grid:
            f.write("".join(line) + "\n")

path_grid = create_path_grid(data)
visualise_path_grid(path_grid)

## D24